post_office/urls.py
from django.conf.urls import url
from django.contrib import admin
from posts.views import index, newpost, userlist, search
from django.views.generic.base import RedirectView, TemplateView
from django.conf.urls import include
from django.contrib.auth import views as auth_views
from cuser.forms import AuthenticationForm
from django.contrib.auth.views import login
from django.contrib.auth.decorators import login_required

urlpatterns = [

    url(r'^accounts/login/$', login, {'authentication_form': AuthenticationForm}, name='login'),
    url(r'^accounts/logout/$', auth_views.logout, kwargs={'next_page': 'home'},
        name='auth_logout'),
    url(r'^register/complete/$', RedirectView.as_view(pattern_name='home'),
        name='registration_complete'),
    url(r'^accounts/', include('registration.backends.simple.urls',
        namespace='accounts')),
    url(r'^accounts/profile/$', login_required(TemplateView.as_view(
        template_name='registration/profile.html')), name='profile'),

    url(r'^$', index, name='home'),

    url(r'^newpost/$', login_required(newpost), name='newpost'),

    url(r'^accounts/(?P<user_id>\d+)/$', userlist, name='userlist'),

    url(r'^search_result/$', search, name='search'),

    url(r'^', include('posts.urls')),

    url(r'^admin/', admin.site.urls),
]

posts/urls.py
from django.conf.urls import url, include
from posts import views
from rest_framework.urlpatterns import format_suffix_patterns
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    url(r'^api/posts/$', views.PostList.as_view()),
    url(r'^api/posts/(?P<pk>[0-9]+)/$', views.PostDetail.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)

urlpatterns += [
    url(r'^api-token-auth/', obtain_auth_token),

]

posts/models.py
from django.db import models
from post_office.settings import AUTH_USER_MODEL

from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token
from django.conf import settings

# Create your models here.


class Posts(models.Model):

    class Meta(object):
        verbose_name = "Post"
        verbose_name_plural = "Posts"
        ordering = ['-datetime']

    title = models.CharField(
        max_length=256,
        blank=False,
        verbose_name="Title"
    )

    datetime = models.DateTimeField(
        auto_now_add=True
    )

    post = models.TextField(
        blank=False,
        verbose_name="Post"
    )

    user = models.ForeignKey(
        AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return "{}-{}".format(self.user, self.title)


@receiver(post_save, sender=AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)

posts/views.py
from django.shortcuts import render, HttpResponseRedirect, render_to_response
from django.core.urlresolvers import reverse
from django.forms import ModelForm
from .models import Posts
from django.contrib.auth import get_user_model
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


from .serializers import PostSerializer
from rest_framework import generics
from rest_framework import permissions
from .permissions import IsOwnerOrReadOnly

# Getting custom User
User = get_user_model()


# Creating form inherited from model
class PostForm(ModelForm):
    class Meta:
        model = Posts
        fields = ['title', 'post']


def index(request):

    # Getting the list of Post objects
    posts = Posts.objects.all()

    paginator = Paginator(posts, 3)  # Show 3 contacts per page

    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        posts = paginator.page(paginator.num_pages)

    return render(request, 'index.html', {'posts': posts})


# View for publishing a new post
def newpost(request):

    newpostform = PostForm(data=request.POST)

    if newpostform.is_valid():
        newpost = newpostform.save(commit=False)
        newpost.user = User.objects.get(id=request.user.id)
        newpost.save()

        newpostform = PostForm()

    posts = Posts.objects.all()

    return render(request, 'newpost.html', {'form': newpostform, 'posts': posts})


# View for getting a list of specified user
def userlist(request, user_id):

    posts = Posts.objects.filter(user=user_id)

    return render(request, 'userlist.html', {'posts': posts})


# View for search
def search(request):

    if 'query' in request.GET and request.GET['query'].strip():
        query = request.GET['query'].strip()
        posts = Posts.objects.filter(post__icontains=query)

        return render_to_response('search_result.html', {'posts': posts, 'query': query})

    else:
        return HttpResponseRedirect('%s?search_message=Please, submit a search term' % reverse('home'))


# REST API
class PostList(generics.ListCreateAPIView):
    queryset = Posts.objects.all()
    serializer_class = PostSerializer
    #permission_classes = (permissions.IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly,)

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)


class PostDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Posts.objects.all()
    serializer_class = PostSerializer
    #permission_classes = (permissions.IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly,)

templates/index.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>POST OFFICE - {% block meta_title %}{% endblock meta_title %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/bootstrap/3.3.0/css/bootstrap.min.css">
    <link rel="stylesheet" href={{ PORTAL_URL }}{% static "main.css" %}>
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-default">
            <h4 class="navbar-text">POST OFFICE</h4>
            <ul class="nav navbar-nav">
                <li><a href="{% url "newpost" %}">New post</a></li>
            </ul>
            <ul class="nav navbar-nav pull-right">
                {% if user.is_authenticated %}
                    <li><a href="{% url "profile" %}">{{ user.email }}</a></li>
                    <li><a href="{% url "accounts:auth_logout" %}">Logout</a></li>
                {% else %}
                    <li><a href="{% url "accounts:auth_login" %}">Login</a></li>
                    <li><a href="{% url "accounts:registration_register" %}">Register</a></li>
                {% endif %}
            </ul>
            </ul>
        </nav>

{% block content %}

{% include "search_form.html" %}

{% include "postlist.html" %}

{% include "pagination.html" %}

{% endblock content %}


    </div>
</body>
</html>

templates/newpost.html
{% extends "index.html" %}

{% block meta_title %}New post{% endblock meta_title %}

<div style="margin-bottom: 20px">
    <form method="get" action={% url "search" %}>

      <input type="search" name="query" />
      <input type="Submit" value="Search" />
      <span>{{ request.GET.search_message }}</span>
    </form>
</div>

{% block content %}

    <div style="margin-bottom: 20px">
        <form method="post" action="{% url 'newpost' %}">
            {% csrf_token %}
            {{ form.as_p }}
          <input type="submit" value="Submit" class="btn"/>
        </form>
    </div>

{% include "search_form.html" %}

{% include "postlist.html" %}

{% endblock content %}

templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if posts.has_previous %}
            <a href="?page={{ posts.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
        </span>

        {% if posts.has_next %}
            <a href="?page={{ posts.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>

templates/postlist.html
{% for post in posts %}

    <p>Author: <a href="{% url "userlist" post.user.id %}">{{ post.user }}</a> | {{ post.datetime }}</p>
    <p>Title: {{ post.title }}</p>
    <p>{{ post.post }}</p>
    <hr>

{% endfor %}

templates/search_form.html
<div style="margin-bottom: 20px">
    <form method="get" action={% url "search" %}>

      <input type="search" name="query" />
      <input type="Submit" value="Search" />
      <span>{{ request.GET.search_message }}</span>
    </form>
</div>

templates/search_result.html
{% extends "index.html" %}

{% block meta_title %}Search result{% endblock meta_title %}

<p>You searched for: {{ query }}</p>

{% block content %}

{% include "postlist.html" %}

{% endblock content %}

templates/userlist.html
{% extends "index.html" %}

{% block meta_title %}User's posts{% endblock meta_title %}

{% block content %}

{% include "postlist.html" %}

{% endblock content %}